name: tests

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/tests.yml'
      - 'tests/test-db-config.xml'
      - 'requirements.txt'
      - 'test-requirements.txt'

jobs:
  tests:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub PostgreSQL image
        image: postgres
        # Provide the info for postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - name: Install requirements
        run: pip install -r requirements.txt -r test-requirements.txt
      - name: Run tests
        run: python -m unittest discover -s "./tests" -t "./tests"
